# Generated by Django 2.0.6 on 2018-06-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contiribution',
            new_name='Contribution',
        ),
    ]
